service: serverless-authorizers

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: serverless-user
  region: us-east-1

  functions:
    authorizeUser:
      handler: authorize.user
    helloRest:
      handler: helloRest.handler
      events:
        - http:
            path: hello/test
            method: get
            authorizer: ${self.custom.authorizer.users}
    helloRestIam:
      handler: helloRestIam.handler
      events:
        - http:
            path: hello/test
            method: get
            authorizer: aws_iam    

custom:
  stage: ${opt:stage, self:provider.stage}
  authorizer:
    users:
      name: authorizerUser
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)