version: "2"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db: {}